---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft.nomanoma-dev.com
  resources:
  - minecraftnetworks
  - minecraftproxies
  - minecraftservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft.nomanoma-dev.com
  resources:
  - minecraftnetworks/finalizers
  - minecraftproxies/finalizers
  - minecraftservers/finalizers
  verbs:
  - update
- apiGroups:
  - minecraft.nomanoma-dev.com
  resources:
  - minecraftnetworks/status
  - minecraftproxies/status
  - minecraftservers/status
  verbs:
  - get
  - patch
  - update
