## Append samples of your project ##
resources:
- minecraft_v1alpha1_minecraftserver.yaml
- minecraft_v1alpha1_minecraftproxy.yaml
- minecraft_v1alpha1_minecraftnetwork.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
