---
apiVersion: minecraft.nomanoma-dev.com/v1alpha1
kind: MinecraftServer
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: survival
spec:
  networkRef: test-network
  type: Paper
  version: "1.20.1"
  eula: true
  whiteList:
    - player1
    - player2
  worldLevel: Normal
  difficulty: Normal
---
apiVersion: minecraft.nomanoma-dev.com/v1alpha1
kind: MinecraftServer
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: creative
spec:
  networkRef: test-network
  type: Paper
  version: "1.20.1"
  eula: true
  worldLevel: Flat
  difficulty: Peaceful
