apiVersion: minecraft.nomanoma-dev.com/v1alpha1
kind: MinecraftProxy
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: proxy
spec:
  networkRef: test-network
  type: Velocity
  version: "latest"
  replicas: 1
