apiVersion: minecraft.nomanoma-dev.com/v1alpha1
kind: MinecraftNetwork
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: test-network
spec:
  proxyRef: proxy
  servers:
    - survival
    - creative
    - lobby
  defaultServer: lobby
