apiVersion: minecraft.nomanoma-dev.com/v1alpha1
kind: MinecraftProxy
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: proxy
spec:
  type: Velocity
  version: 3.1.2
  replicas: 1
